# Generated by Django 4.1.1 on 2022-09-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crazy_book_clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
    ]
