# Generated by Django 4.1.1 on 2022-09-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crazy_book_clubs', '0004_book_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='text',
        ),
    ]
